# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту IuriyG@protonmail.com если сборка упала
notifications:
  email:
    recipients:
      -IuriyG@protonmail.com
    on_success: never # default: change
    on_failure: always # default: always

    # ключ с сайта https://codecov.io
    env:
      global:
        - CODECOV_TOKEN="c281b161-7335-4822-b2d6-44cf1fd22a64"
